[test_config]
# Set the type of coverage to be run:
# - 'line' for line coverage (default)
# - 'branch' for branch coverage
line-coverage = true
branch-coverage = true

# Directory to output coverage files and reports.
output-dir = "./target/tarpaulin"

# Build all packages in the workspace.
workspace = true

# List of file paths to exclude from testing.
exclude-files = [
    "crates/sentinel/benches/**",
    "**/main.rs",
    # Excluded because this is just "glue" code for the CLI
    "crates/cli/src/cli.rs",
    # Excluded because this is just logging setup
    "crates/cli/src/logging.rs",
]

[report]
# Format of the coverage report (e.g., "Stdout", "Html", "Xml", "Lcov").
out = ["Xml", "Html", "Stdout"]

# Directory to output coverage files and reports.
output-dir = "./target/tarpaulin"
